
name: tennis-ai
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.6.6
  - conda-forge::pyodbc
  - conda-forge::spacy==2.0.12
  - conda-forge::tensorflow==1.10.0
  - flask
  - pyopenssl
  - conda-forge::opencv
  - keras
  - Jinja2==2.10
  - pandas